- floodlight/core/definitions.py
- floodlight/core/events.py
Added some basic functionality (getter/setter, tests, find, add frameclock) to the Events object.
> feat: events

- floodlight/core/definitions.py
- floodlight/core/events.py
This merge includes several methods for handling the ``Events`` object:
* __getitem__ and __setitem__ dunders
* column definitions and checks
* column checks for soft convention enforcement
* add_frameclock method
* select method for advanced querying
> feat: basic events functionality

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- auto-changelog will generate a new changelog by executing
auto-changelog -t changelog -v [version]
https://github.com/KeNaCo/auto-changelog
> chore: add changelog generator

- tests/test_core/conftest.py
- tests/test_core/test_events.py
Some tests for the Events class
> test: events

- floodlight/core/events.py
- tests/test_core/conftest.py
- tests/test_core/test_events.py
- Translates xy data by shift vector
> feat: transformation methods for events object

- pyproject.toml
- tests/test_core/conftest.py
- tests/test_core/test_events.py
Update tests for the core class events now containing all previously missing functions. 
In addition also update the pyproject toml file to ignore user warnings during pytest to enable warnings-free testing even with (possibly) problematic structures.
> test: update tests for events core class

- tests/test_core/test_events.py
The final missing test for the events core class.
> test: column_in_range method

- docs/source/modules/models/kinematics.rst
- floodlight/models/kinematics.py
- tests/test_models/conftest.py
- tests/test_models/test_kinematics.py
This PR includes the initial version of an object oriented approach to modeling the kinematics of players on the pitch regarding New Models in Issue #38. In this first draft I focused on calculating the euclidean distances of players as a `PlayerProperty`.
Although there is much room for improvement regarding documentation and testing, I would love some feedback on the general demand of this approach and the structure of the data class, as this could be used as a template for further kinematic and kinetic models, like speed and acceleration. Also some feedback about the structure of documentation inside classes would be much appreciated.
> feat: add kinematics module - distance, velocity, acceleration models

- floodlight/core/pitch.py
- floodlight/io/opta.py
- floodlight/io/statsperform.py
- tests/test_core/test_pitch.py
Expand the StatsPerform parser with functions to read the internal format for position and event data.
> feat: add statsperform parser - standard format

- floodlight/io/kinexon.py
- floodlight/models/kinetics.py
These are just minor fixes for typos etc.
> fix: minor fixes

- floodlight/io/dfl.py
- floodlight/io/statsperform.py
- update dfl parser to newest version
- convert gameclock of statsperform parser from milliseconds to seconds
> fix: adapt dfl parser to different format versions and fix statsperform gameclock unit

- floodlight/transforms/filter.py
- tests/test_transforms/conftest.py
- tests/test_transforms/test_filter.py
fixes a bug in the filter module that resulted in wrong handling of the minimum signal length
> fix: minimum signal length

- floodlight/core/teamsheet.py
- tests/test_core/test_teamsheet.py
Add the class method add_xIDs() to the Teamsheet class.
> feat: add xIDs

- .pre-commit-config.yaml
- docs/source/modules/io/io.rst
- docs/source/modules/io/sportradar.rst
- floodlight/io/sportradar.py
This is the initial and undocumented version of a parser for the raw SportRadar Timeline data in .json format. Work is still in progress but feedback is already appreciated as the general structure should stay pretty much the same. The next commits will add documentation and typing.
> feat: Sportradar parser

- floodlight/io/secondspectrum.py
BREAKING CHANGE: replaces link creation functions with teamsheet parsing functions
> feat!: integrate teamsheet logic to secondspectrum parsers

- floodlight/io/tracab.py
BREAKING CHANGE: replaces link creation functions with teamsheet parsing functions
> feat!: integrate teamsheet logic to tracab parser

- docs/source/guides/getting_started.rst
- docs/source/guides/tutorial_matchsheets.rst
- floodlight/io/datasets.py
- floodlight/io/dfl.py
- floodlight/io/opta.py
- floodlight/io/secondspectrum.py
- floodlight/io/statsbomb.py
- floodlight/io/statsperform.py
- floodlight/io/tracab.py
- tests/test_io/test_datasets.py
BREAKING CHANGE: this changes the return signature of all public parsing functions
> refactor!: flexible dictionary returns for parser

- floodlight/io/datasets.py
Assign None to cases where stadium is missing in StatsBomb dataset.
> fix: statsbomb dataset

- docs/source/guides/tutorial_matchsheets.rst
Fix an error that occurs because there was a change in the structure of the StatsBomb dataset.
> fix: statsbomb tutorial

- floodlight/core/pitch.py
- floodlight/io/statsperform.py
Pass the keyword sport when creating the Statsperform Pitch.
Update the Typing to int segments.
> fix: statsperform parser

- floodlight/io/dfl.py
> fix: docstrings

- docs/source/guides/contrib_manual.rst
The command to install poetry via PowerShell has changed. This PR updates the docs with the new command.
> docs: poetry install command

- floodlight/io/kinexon.py
This PR adds the feature to add a custom column delimiter when parsing Kinexon.csv data. Tested this with a semicolon-seperated values file without problems.
> feat: kinexon delimiter

- .github/workflows/build.yaml
- .readthedocs.yaml
- CHANGELOG.md
- README.md
> build: release 1.0.0
